### ISSUE TITLE
Length of Title field

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#1]
Bei der Anmeldung einer Thesis kann der Titel 202 (und wahrscheinlich noch mehr Zeichen haben), bei der Benotung kommt es dann aber zu einem Validation Error, der das (dort nicht zu änderne) Feld Titel anmeckert, welches in dieser Maske nur 200 Zeichen lang sein darf.
Reproduzierbar: Ja
Workaround: Benotung abbrechen, Eintrag editieren und Titel auf 200 Zeichen kürzen und erneut benoten, dann geht es.
Gewünscht: Gleich bei der Erfassung sollte der Titel auf eine Maximallänge von 200 Zeichen begrenzt werden.

**Comment by LinusKanstein** [comment]
Länge ist in der neuen Version jetzt begrenzt.
Eigentliche max_länge war 300 Zeichen begrenzt, wurde in zweiter Bedingung auf 200 Zeichen geändert, was erst beim ändern einen Fehler gab.
Gibt es einen speziellen Grund, warum der Titel maximal 200 Zeichen sein darf? Die anderen Felder haben bisher auch eine max_länge von 300 Zeichen.

**Comment by thomsmits** [comment]
Es gibt - soweit ich weiß - keinen Grund für eine Längenbeschränkung. Vielleicht wegen des PDF-Formulars?

**Comment by LinusKanstein** [comment]
Länge des Titels bleibt erstmal auf 200 Zeichen.
Länge vom externen Arbeitsplatz wurde auch vereinheitlicht (200 Zeichen), das hätte den selben Fehler verursachen können.
