### ISSUE TITLE
Falscher Text im Formular für Masterarbeiten

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#10]
bei der Anmeldung von *Master*arbeiten generiert der Formulargenerator
des Thesis-Pools auch den folgenden Satz in das Formular, der aber nur
für Bachelorarbeiten stimmt:
"Ich nehme die gestellte Aufgabe an und bestätige mit meiner
Unterschrift, dass ich alle Prüfungsleistungen aus den ersten fünf
Studiensemestern bestanden habe."

**Comment by LinusKanstein** [comment]
Von welchem Formular reden Sie? den PDFs, die man generieren kann?

**Comment by thomsmits** [comment]
Das Problem hat sich mit den neuen Formularen erledigt. Der Text steht jetzt weder auf dem Bachelor, noch dem Masterarbeitsformular. Also gibt es auch nichts mehr zu beheben.

Ich schließe das Ticket.
