### ISSUE TITLE
Noten für BA getrennt nach Korrektor eingeben

### ISSUE THREAD

**Issue by sacharpaulus** [informatik-mannheim/faculty-thesis-db#11]
Das PA fordert, dass die beiden Korrektoren / Gutachter die Noten separat vergeben, und dass dann der Durchschnitt berechnet wird (steht so auch in der SPO). 
Das Tool unterstützt das bisher nicht. Es wäre toll, wenn das Tool die Notenerfassung separat ermöglichen würde.

**Comment by tillnagel** [comment]
Aktuelles Formular bietet diese Funktion. Ich schließe mal. Falls was anderes gemeint war, bitte wieder öffnen.

**Comment by thomsmits** [comment]
Leider bietet es zwar das Formular, nicht aber die Webanwendung. Aktuell wird die Note nur einmal erfasst und dann einfach in beide Felder eingetragen.

**Comment by LinusKanstein** [comment]
Die Funktion für eine zweite Note habe ich in der Version für django4 ergänzt.
Der Name des Feldes lautet bisher 'second_grade', der wird aber noch verändert.
Beim Bewerten handelt es sich bei der Zweitkorrektor-Note um kein Pflichtfeld, da assessor auch kein pflichtfeld ist.
In der Overview werden beide Noten bisher nebeneinander angezeigt, beispielhaft: '1.0 | 2.0'.

Die zweite Note muss noch auf die Bewertungs-pdf konfiguriert werden und ich werde ein paar tests ergänzen / neu schreiben.

**Comment by LinusKanstein** [comment]
Zweitkorrektor Note und Gesamtnote werden jetzt im bewertungs-pdf eingetragen
tests zu pdf erneuert und ergänzt, die bisherigen pdfs wurden alle ausgetauscht
