### ISSUE TITLE
Applikation crasht bei Sonderzeichen im Titel der Arbeit

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#12]
Wenn der Titel der Arbeit Sonderzeichen enthält, crasht die PDF-Generierung. Z.B. führt der Titel "<<< Titel >>>" zu einem Absturz.

**Comment by LinusKanstein** [comment]
Bevor die Daten in die PDFs eingefügt werden, erfolgt eine Zwischenspeicherung in einem xfdf-dokument, welches auf xml basiert. Das Nutzen der Zeichen <> führt zu einem Fehler, da xfdf diese als Versuch einen Tag zu erstellen interpretiert.
Ein Dokument sähe beispielhaft so aus:
![image](https://user-images.githubusercontent.com/86070097/173513485-15fe0c63-3110-4b43-9f39-f87ef0f64229.png)

Bei anderen Sonderzeichen (zb ? oder !) trat der Fehler bisher bei meinen Tests nicht auf.
Eine schnelle Lösung für das Problem fällt mir bisher nicht ein.

**Comment by thomsmits** [comment]
Kann man die Zeichen vielleicht durch Entitäten ersetzen oder eine CDATA-Sektion verwenden?

**Comment by LinusKanstein** [comment]
Entitäten funktionieren, verbesserten Code pushe ich demnächst.
