### ISSUE TITLE
Nach "Einreichen" der Arbeit wird Abgabedatum in falsches Feld im PDF eingetragen

### ISSUE THREAD

**Issue by tillnagel** [informatik-mannheim/faculty-thesis-db#13]
Wenn eine Arbeit über den Button "Einreichen" abgegeben wird, ist im Folgeformular ein Abgabedatum einzutragen. Vorausgewählt ist das avisierte Datum. Auch bei Belassen dieses Original-Datums wird das im "Bewertung"-PDF dann an die Stelle "verspätet am" eingetragen. Korrekt wäre aber bei "war abzugeben bis".

**Comment by LinusKanstein** [comment]
Das Problem wurde mit dem Austauschen der PDFs mit den neuen Versionen dieser gelöst.
