### ISSUE TITLE
Vorausfüllen des Formulars für eine Verlängerung im Krankheitsfall unterstützen

### ISSUE THREAD

**Issue by oliverhummel** [informatik-mannheim/faculty-thesis-db#14]
s. hier: https://www.hs-mannheim.de/fileadmin/user_upload/hauptseite/pdf/Formulare_Bilder_Studium/verlaengerung_bachelor_master_krankheit.pdf

**Comment by LinusKanstein** [comment]
Ich schließe diesen Thread da es einen neuen gibt, der das gleiche Thema behandelt.
