### ISSUE TITLE
Liste der Abschlussarbeiten sortiertbar (und filterbar) machen

### ISSUE THREAD

**Issue by oliverhummel** [informatik-mannheim/faculty-thesis-db#15]
Bisher erschließt sich mir die Sortierung nicht (wirklich). Anfangs ist es nach Datum sortiert, aber dann am Ende doch wieder nicht.

Eine Sortierung nach den verschiedenen Spalten (durch Klick) auf die Überschriften wäre schön, evtl. wäre auch eine Filterfunktion hilfreich o. zumindest ein einstellbares Ausblenden von älteren Arbeiten.

**Comment by thomsmits** [comment]
Die Liste ist schon sortiert aber unterschiedlich für angemeldete und abgegebene Arbeiten:

Angemeldete Arbeiten: Nach Enddatum absteigend (Jahr scheint nicht beachtet zu werden)
Abgegebene Arbeiten: Nach Abgabedatum aufsteigend

**Comment by oliverhummel** [comment]
Ähnlich zu #9, nur weitreichender. Ich fände es gut, wenn die Sortierung frei über die Tabelle im Frontend passieren könnte.

**Comment by LinusKanstein** [comment]
In die Version für django4 eingearbeitet

Beim klicken auf die Überschriften wird die Tabelle nach diesem Attribut neu sortiert.
Bei Student und Zweitkorrektor erfolgt dies nach dem Nachnamen; wenn es keinen Zweitkorrektor gibt diese Thesen nach hinten sortiert.

Eine Suchleiste gibt es nun auch, bei Student kann man sowohl nach einer Matrikelnummer, als auch nach dem Namen suchen.

Die beiden Funktionen gehen noch nicht ganz hand in hand, falls man erst sucht und dann sortiert, gehen die Suchparameter verloren. Daran wird noch gearbeitet.

**Comment by LinusKanstein** [comment]
Code überarbeitet.

Ergänzt:
Falls nach einem Abgabedatum gesucht wird, werden alle Thesen ab diesem Datum angezeigt.
Sortierparameter bleiben nun erhalten.
Sortierung wird beim drücken des Suchbuttons zurückgesetzt.

**Comment by LinusKanstein** [comment]
Neues Feature: Sortierung wird beim erneuten drücken des selben tags umgedreht
