### ISSUE TITLE
Verlängerung bei Krankheit

### ISSUE THREAD

**Issue by oliverhummel** [informatik-mannheim/faculty-thesis-db#16]
Es gibt ein neues Formular für die Verlängerung von Arbeiten im Krankheitsfall, das vom Arzt auszufüllen und direkt vom Studierenden an den Prüfungsausschussvorsitzenden zu senden ist.

Bitte auch das bzw. den Link dahin (https://www.hs-mannheim.de/fileadmin/user_upload/hauptseite/pdf/Formulare_Bilder_Studium/verlaengerung_bachelor_master_krankheit.pdf) in das System einbauen.

**Comment by LinusKanstein** [comment]
Funktion ist in der version für django4 ergänzt
pdf ist im System unter website/pdf hinzugefügt
