### ISSUE TITLE
Matrikelnummer wird seit WiSe 2021/2022 recycled

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#17]
Die Matrikelnummer wird seit dem Wintersemester 2021/2022 bei einem Wechsel des Studiengangs beibehalten. Wenn also beispielsweise ein Student von Bachelor in den Master wechselt, bleibt die Nummer erhalten. In Folge ist die Matrikelnummer kein eindeutiger Schlüssel mehr für den Studiengang, sondern nur noch für die Person. Um die Daten auch retrospektiv revisionssicher abzulegen, sollte der Studiengang in den Datensatz der Abschlussarbeit übernommen werden und nicht aus dem Studentenstammsatz stammen. Andernfalls könnten sonst aus Bachelorarbeiten plötzlich Masterarbeiten werden.

Dasselbe gilt für einen Wechsel zwischen Bachelor-Studiengängen.

**Comment by LinusKanstein** [comment]
Dem Thesis-Modell wurde ein neues Feld hinzugefügt (thesis_program).
Beim erstellen einer Thesis wird der aktuelle Studiengang in der Thesis gespeichert und kann nur in der Admin-Seite wieder geändert werden.

**Comment by thomsmits** [comment]
Es scheint so, als ob das zwar für alte Arbeiten funktioniert, man aber keine neue Arbeit anlegen kann.

Beispiel:
Person hat bereits IMB studiert
Person schreibt Bachelorarbeit in IMB
Person wechselt in den Master und behält Matrikelnummer
Beim Anlegen der Masterarbeit wird weiterhin eine Bachelorarbeit angelegt, weil das System den falschen Studiengang gecached hat.

**Comment by LinusKanstein** [comment]
Ich habe unter StudentManager den Code angepasst, damit beim suchen nach einem Studenten in der Fakultäts-datenbank der Eintrag in der thesis-Datenbank aktualisiert wird. 
Vorher wurde, wenn der Studierende bereits in der thesis-Datenbank existiert (z.B. durch eine Bachelorthesis) das Objekt genommen und nicht in die Fakultätsdatenbank geschaut, ob es Änderungen bei dem Studierenden gab.

Die alten Thesen des Studierenden werden von der Änderung nicht betroffen, da der Studierngang beim Erstellen der Thesis abgespeichert wird und nicht verändert werden kann (außer ein admin macht das manuell).
