### ISSUE TITLE
Studierende aus anderen Fakultäten eintragbar machen

### ISSUE THREAD

**Issue by tillnagel** [informatik-mannheim/faculty-thesis-db#3]
Ich betreue derzeit eine Studentin aus der Gestaltung als Erstbetreuer zu einem informatiknahem Thema. Wenn ich im Tool die Matrikelnummer dieser Studentin eingebe, wird diese nicht gefunden, und der Hinweis "Matrikelnummer existiert nicht" angezeigt.

**Comment by thomsmits** [comment]
Wir haben keine Stammdaten von anderen Fakultäten, da wir nur unsere eigenen Studierenden kennen. Insofern ist das zur Zeit nicht umsetzbar, da wir die Daten der Studierenden aus den Stammdaten beziehen.

Man müsste für solche Fälle eine Freitexteingabe vorsehen. Das ist ein Feature mit nicht unerheblichem Implementierungsaufwand und daher erst beim nächsten Release (so es eins geben wird) umsetzbar.

**Comment by tillnagel** [comment]
Verstehe. Work-around also: im Nachhinein händisch nachtragen.

**Comment by thomsmits** [comment]
Wir lassen es mal auf der Wunschliste.

**Comment by LinusKanstein** [comment]
In der Version für django 4 ergänzt.
In der Seite wo nach Studenten gesucht wird, lassen sich nun Studenten anderer Fakultäten ergänzen. Diese müssen zuerst separat erstellt werden (neuer Button) und können danach in der Suche gefunden werden. Neue Studenten werden in der lokalen Datenbank abgespeichert. Bei der Erstellung werden die Matrikelnummern mit allen Studenten in der Fakultäts-Datenbank und der lokalen Datenbank abgeprüft.
