### ISSUE TITLE
Logout with Back Button

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#4]
Nach einem Logout bei Firefox und einem Klick auf den Back-Button ist man wieder in der Übersicht... Sollte so m.E. nicht sein. Bei Chrome ist das anders.

**Comment by LinusKanstein** [comment]
Chrome führt einen reload nach Nutzen des Back-buttons aus. Firefox hingegen lädt die letzte Seite aus dem Cache ohne einen get/post-request auszuführen (lässt sich beim developer-modus im terminal verfolgen). Beim laden einer neuen Seite wird man dann auf die login-Seite weitergeleitet, der Logout findet also statt.

Eine mögliche Lösung müsste vermutlich über JavaScript erfolgen, bisher leider mit mäßigem Erfolg. In der HTML-Seite onLoad="window.location.reload();" zu nutzen funktioniert nicht, da die Seite nur aus dem Cahce geladen wird. Was funktionieren würde wäre ein reload nach einem bestimmten Zeitintervall.

**Comment by LinusKanstein** [comment]
Ich hätte gar nicht erst versuchen sollen mich in JS einzulesen, das Problem kann man in Backend lösen.
Django stellt einen methoden-decorator names "never_cache" bereit, welcher im HTTP-Header das Caching der Seite verhindert. Die Lösung ist zwar nicht unbedingt optimal, jedoch Zeitsparender als sich weiter in den Tiefen von JS zu verlieren.
