### ISSUE TITLE
Arbeiten löschen können, wenn noch keine Statusänderungen passiert sind

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#5]

**Comment by oliverhummel** [comment]
+1: neu angelegte Arbeiten sollten wieder gelöscht werden können, so lange noch keine Formulare für sie generiert worden sind.

**Comment by LinusKanstein** [comment]
Ergänzt in Version für django 4

Thesen können in der Änderungssicht gelöscht werden. Das ganze funktioniert aber nur, sofern sich der status und excom_status nicht geändert haben. Test wurden auch schon hinzugefügt.
Spezifisch: beide Felder müssen noch den Wert APPLIED besitzen und es darf kein Verlängerungsdatum oder Einreichungsdatum geben.

Bei der Ergänzung von oliverhummel bin ich mir nicht ganz sicher was gemenit ist.
