### ISSUE TITLE
Give special access to head of examination board

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#6]
Currently a professor has only access to his/her own students. The head of the examination board should be able to see all - as currently already the secretaries.

**Comment by LinusKanstein** [comment]
Dem User-Modell wurde ein neues Feld hinzugefügt (is_head).
Als solche markierte Nutzer können alle Thesen sehen, jedoch neue Thesen nur für sich selber erstellen. Implizit wird also vorrausgesetzt, dass es sich auch immer um Supervisor handelt
Da das Feld im ldap bisher nicht eistiert muss die Vergabe manuell in der Admin-Seite erfolgen.
