### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#7]
ValidationError at /change/
{'prolongation_date': ['prolongation date must be later than due date']}
Request Method: POST
Request URL: https://thesis.informatik.hs-mannheim.de/change/
Django Version: 1.11.1
Exception Type: ValidationError
Exception Value: {'prolongation_date': ['prolongation date must be later than due date']}
Exception Location: /usr/local/lib/python3.5/dist-packages/django/db/models/base.py in full_clean, line 1248
Python Executable: /usr/bin/python3
Python Version: 3.5.2
Python Path: ['/var/www/thesispool',
'/usr/lib/python35.zip',
'/usr/lib/python3.5',
'/usr/lib/python3.5/plat-x86_64-linux-gnu',
'/usr/lib/python3.5/lib-dynload',
'/usr/local/lib/python3.5/dist-packages',
'/usr/lib/python3/dist-packages']
Server time: Di, 19 Mär 2019 11:29:49 +0100

**Comment by LinusKanstein** [comment]
Es ist mir nicht gelungen den Fehler zu reproduzieren. Bei verlängerten Thesen konnte ich bei der Bearbeitung das Abgabedatum nicht später setzen als das Verlängerungsdatum.

**Comment by thomsmits** [comment]
Ich glaube, der Fehler bezog sich darauf, dass das neue, verlängerte Abgabedatum vor dem eigentlichen Abgabedatum lagt. Die Arbeit also nicht verlängert, sondern verkürzt wird.

**Comment by LinusKanstein** [comment]
Der Fehler tritt auf, wenn eine verlängerte Thesis geändert wird und das neue Abgabedatum später als das Verlängerungsdatum liegt. Es ist mir bisher nicht gelungen, im Formular selber eine Fehlermeldung zu erzeugen.

Übergangsmäßig wird das Verlängerungsdatum neben das Eingabefeld schreiben, an einer besseren Lösung wird gearbeitet

**Comment by LinusKanstein** [comment]
Neue Lösung: Das Verlängerungsdatum wird beim ändern einer Thesis mit übergeben und als DateField mit HiddenWidget genutzt.
Falls due_date > prolongation_date wird ein Fehler im Formular erzeugt (anstelle des obrigen Fehlers).
Tests wurden ergänzt.
