### ISSUE TITLE
Bearbeiten nach Notenabgabe

### ISSUE THREAD

**Issue by blueboffin** [informatik-mannheim/faculty-thesis-db#8]
nach Notenabgabe ist kein Editieren mehr möglich, was dumm ist, wenn der Zweitgutachter feststellt, dass auf dem ausgedruckten Bewertungsformular das Kolloq.-Datum falsch ist...

**Comment by LinusKanstein** [comment]
Im Branch geändert: die Buttons zum Ändern und Bewerten sind jetzt nach der Benotung noch verfügbar.
