### ISSUE TITLE
Sortierung der Arbeiten nach der Benotung

### ISSUE THREAD

**Issue by thomsmits** [informatik-mannheim/faculty-thesis-db#9]
Abgeschlossene Arbeiten nicht nach unten verschieben, sondern die Arbeiten immer mit dem spätesten Abgabedatum nach oben sortiert anzeigen.

**Comment by mgroeschel** [comment]
Fände ich auch ein eine hilfreichere Sortierung. Pflegt das noch jemand? - Issue ist ja schon länger offen ...

**Comment by LinusKanstein** [comment]
Die Thesen lassen sich in der neuen Version nach jedem Attribut (Abgabedatum etc) sortieren. Sortierung wird beim erneuten drücken des Attributnames in der Overview umgedreht.

**Comment by mgroeschel** [comment]
Bei mir lässt sich nichts sortieren (Firefox und Chrome gestestet). Ist die Veränderung schon ausgeliefert?

**Comment by LinusKanstein** [comment]
Tut mir leid, ich hätte mich etwas klarer ausdrücken sollen. Alle von mir vollzogenen Änderungen beziehen sich auf den Branch (version_for_django_4) des Projektes, welcher bisher noch nicht genutzt wird. An der derzeit laufenden Version werde ich keine Veränderungen vornehmen.
